[package]

name = "glutin"
version = "0.0.2"
authors = ["tomaka <pierre.krieger1708@gmail.com>"]
description = "Cross-plaform OpenGL context provider."
keywords = ["windowing", "opengl"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/tomaka/glutin"

[features]
default = ["window"]
window = []
headless = []

[dependencies.gl_generator]
git = "https://github.com/bjz/gl-rs"

[dependencies.gl_common]
git = "https://github.com/bjz/gl-rs"

[target.arm-linux-androideabi.dependencies.android_glue]
git = "https://github.com/servo/android-rs-glue"

[target.i686-apple-darwin.dependencies.cocoa]
git = "https://github.com/servo/rust-cocoa"

[target.x86_64-apple-darwin.dependencies.cocoa]
git = "https://github.com/servo/rust-cocoa"

[target.i686-apple-darwin.dependencies.core_graphics]
git = "https://github.com/servo/rust-core-graphics"

[target.x86_64-apple-darwin.dependencies.core_graphics]
git = "https://github.com/servo/rust-core-graphics"

[target.i686-pc-windows-gnu.dependencies.winapi]
git = "https://github.com/retep998/winapi-rs"
features = ["gdi32", "kernel32", "user32"]

[target.x86_64-pc-windows-gnu.dependencies.winapi]
git = "https://github.com/retep998/winapi-rs"
features = ["gdi32", "kernel32", "user32"]
